env: "local" #local, dev, prod
storage_path: "./storage/storage.db"
migrations_path: "./migrations"

http_server:
  address: "localhost:8888"
  timeout: 4s
  idle_timeout: 60s

postgresql:
  user: user
  password: password
  dbname: mydatabase
  sslmode: disable 
  host: localhost
  port: 5432

kafka:
  brokers: ["localhost:9092"]
  consumer_group: orders-group
  topic: orders

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
